### ISSUE TITLE
Add shadow to tab bar bottom.

### ISSUE THREAD

**Issue by Los83** [react-component/m-tabs#10]
I am trying to add a shadow to the bottom of the tab bar for android with: 
```    elevation: 4,
    shadowColor: 'rgba(0,0,0,.1)',
    shadowOffset: {
      width: 0,
      height: StyleSheet.hairlineWidth,
    },
    shadowRadius: StyleSheet.hairlineWidth
```
I tried adding the style to the tab container, to the tabs themselves but for some reason that does not work.  Any clue as to why this doesn't work?

**Comment by zhang740** [comment]
shadow props only support ios.
https://facebook.github.io/react-native/docs/shadow-props.html
@Los83

**Comment by Los83** [comment]
shadowColor: 'rgba(0,0,0,.1)',
    shadowOffset: {
      width: 0,
      height: StyleSheet.hairlineWidth,
    },
    shadowRadius: StyleSheet.hairlineWidth

**Comment by Los83** [comment]
sorry forgot to add the elevation here.  This still doesn't work either.
``` 
    elevation: 4,
    shadowColor: 'rgba(0,0,0,.1)',
    shadowOffset: {
      width: 0,
      height: StyleSheet.hairlineWidth,
    },
    shadowRadius: StyleSheet.hairlineWidth
```
