### ISSUE TITLE
Rewrite tabBar

### ISSUE THREAD

**Issue by HuBinAdd** [react-component/m-tabs#11]
https://github.com/react-component/m-tabs/blob/f1d276ee7d7fdd14b59465b6ecf6fe404756403b/src/Tabs.tsx#L237
在ios下使用position:sticky时,由于tabBar无高度导致sticky失效，可以剔除这一层吗或者支持重写，
content同理

**Comment by zhang740** [comment]
https://react-component.github.io/m-tabs/examples/sticky.html
第二种怎么样？ @HuBinAdd
