### ISSUE TITLE
Enable Mouse Events

### ISSUE THREAD

**Issue by tOke3i** [react-component/m-tabs#3]
Hi! Is it possible to enable Mouse Events(I mean to swipe through tabs by mouse on desktop) using your plugin?

**Comment by zhang740** [comment]
cc @paranoidjk

**Comment by paranoidjk** [comment]
Sorry, [rc-gesture](https://github.com/react-component/gesture) only support TouchEvent right now. And i think support swipe in pc is worthless, it's a rare usecase.
