### ISSUE TITLE
tab bar's previous page and next page not behave as expected

### ISSUE THREAD

**Issue by hhking** [react-component/m-tabs#8]
1. set tabbar's tab number to 3, 
2. switch to the middle tab,
3. the tabbar's previous page or next page will not show as expected.

![image](https://user-images.githubusercontent.com/11470599/31655900-e5d4cd50-b2ef-11e7-8ac6-fc7aa13e8326.png)
![image](https://user-images.githubusercontent.com/11470599/31655910-ea60a48e-b2ef-11e7-97c6-9a089f9de7c2.png)
![image](https://user-images.githubusercontent.com/11470599/31655918-ee43ad58-b2ef-11e7-80dc-a87673112406.png)
![image](https://user-images.githubusercontent.com/11470599/31655926-f29d70be-b2ef-11e7-91ef-f92d941ed8fa.png)

**Comment by hhking** [comment]
God job！
But now, in the initial(before switch the tab), the tabbar's next page will not show.
@zhang740

**Comment by zhang740** [comment]
`But now, in the initial(before switch the tab), the tabbar's next page will not show.`
how to reproduce?
@hhking

**Comment by hhking** [comment]
![image](https://user-images.githubusercontent.com/11470599/31703337-c3feff5e-b3a1-11e7-84c4-7305c9d7edfb.png)
open the page, and do not switch the tab, the tabbar's next page will not show. @zhang740

**Comment by zhang740** [comment]
![image](https://user-images.githubusercontent.com/7530656/31707831-00723418-b3b3-11e7-8aa5-d50536aaed3c.png)
where is different from example? https://react-component.github.io/m-tabs/examples/scroll-tab.html
@hhking

**Comment by hhking** [comment]
I find the reason.
the initial value of my tabs  is Empty array(tabs = []), and change the value of tabs by setState.
@zhang740

**Comment by zhang740** [comment]
fix on 1.2.10
@hhking
